apiVersion: v1
kind: Service
metadata:
  name: my-spring-boot-app-service
  labels:
    app: spring-boot-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot-app
  type: LoadBalancer
